# Generated by Django 4.2.5 on 2024-08-12 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        default="", max_length=255, verbose_name="username"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        default="", max_length=255, verbose_name="password"
                    ),
                ),
                (
                    "createTime",
                    models.DateField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={"db_table": "user",},
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "jobId",
                    models.CharField(default="", max_length=255, verbose_name="职位ID"),
                ),
                ("count", models.IntegerField(default=1, verbose_name="收藏次数")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myApp.user"
                    ),
                ),
            ],
            options={"db_table": "history",},
        ),
    ]
